server:
  port: 3001

spring:
  jpa:
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:testdb'

#spring.jackson.default-property-inclusion: NON_NULL


#spring.data.jpa.repositories.bootstrap-mode=default